AWSTemplateFormatVersion: "2010-09-09"
Description: MFM Project Cumulative Canary Alarms Template

Transform:
  Name: 'AWS::Include'
  Parameters:
    Location: 's3://cyc-prd-repository/infra/product/mfm/cycmfmglobalvariables.yml'

Conditions:
  Valid: !Equals [!FindInMap [Infra, !Ref "AWS::AccountId", Envr], cyc]

Resources:

  ecsclientalarm:
    Type: 'AWS::CloudFormation::Stack'
    Condition: Valid
    Properties:
      TemplateURL: 'https://cyc-prd-repository.s3.amazonaws.com/infra/product/mfm/cycmfm-alarms-ecs-client-stack.yml'